/**
 * @file miller-rabin.h
 * @brief Auto-generated header for miller-rabin.c
 *
 * Generated by Header File Generator on 2026-10-01.
 * DO NOT EDIT — re-run the generator to update.
 */

#ifndef MILLER_RABIN_H
#define MILLER_RABIN_H

#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef unsigned long long ull;

ull mulmod(ull a, ull b, ull mod);
ull powmod(ull base, ull exp, ull mod);
bool miller_rabin_deterministic(ull n);

unsigned long long random_uint64();
unsigned long long randint_large(unsigned long long min, unsigned long long max);
unsigned long long get_random_prime(unsigned long long min, unsigned long long max);

#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* MILLER_RABIN_H */
